# Generated by Django 4.0.10 on 2023-03-17 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userAuth',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('roll', models.CharField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Farmers',
            fields=[
                ('farmer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fName', models.CharField(max_length=254)),
                ('lName', models.CharField(max_length=254)),
                ('location', models.JSONField(default=dict, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='IN')),
                ('email', models.EmailField(default=None, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fName', models.CharField(max_length=254)),
                ('lName', models.CharField(max_length=254)),
                ('location', models.JSONField(default=dict, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128, region='IN')),
                ('email', models.EmailField(default=None, max_length=254)),
            ],
        ),
    ]
