# Generated by Django 4.0.10 on 2023-03-20 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinventory',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Authentication.allproductlist'),
        ),
    ]
