# Generated by Django 4.0.10 on 2023-03-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_alter_vendor_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmers',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
