# Generated by Django 4.0.10 on 2023-03-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_alter_productinventory_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproductlist',
            name='products',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
