# Generated by Django 4.0.10 on 2023-03-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_productinventory_productquantityleftininventory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinventory',
            name='farmerLocation',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
