# Generated by Django 4.0.10 on 2023-03-20 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_alter_allproductlist_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allproductlist',
            old_name='products',
            new_name='productName',
        ),
    ]
