# Generated by Django 4.0.10 on 2023-03-21 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_remove_productinventory_productquantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinventory',
            old_name='unit',
            new_name='productQunatity',
        ),
        migrations.RenameField(
            model_name='productinventory',
            old_name='unitValue',
            new_name='productUnit',
        ),
    ]
