# Generated by Django 4.0.10 on 2023-03-18 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_alter_farmers_email_alter_vendor_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField(null=True)),
                ('listedDate', models.DateField()),
                ('expiryDate', models.DateField()),
                ('images', models.TextField(default='[]', null=True)),
                ('quantity', models.JSONField(default=dict, null=True)),
                ('farmerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.farmers')),
            ],
        ),
    ]
