# Generated by Django 4.0.10 on 2023-03-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_productinventory_currentbidprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinventory',
            name='productQuantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='productQuantityLeftInInventory',
            field=models.IntegerField(null=True),
        ),
    ]
