# Generated by Django 4.0.10 on 2023-03-20 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_rename_products_allproductlist_productname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmers',
            old_name='farmer',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='vendor',
            new_name='id',
        ),
    ]
