# Generated by Django 4.0.10 on 2023-03-22 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_rename_unit_productinventory_productqunatity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinventory',
            old_name='productQunatity',
            new_name='productQuantity',
        ),
    ]
