# Generated by Django 4.0.10 on 2023-03-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_alter_productinventory_productquantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmers',
            name='farmerRatings',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='VendorRatings',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
