# Generated by Django 4.0.10 on 2023-03-18 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_alter_product_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductInventory',
        ),
    ]
