# Generated by Django 4.0.10 on 2023-03-24 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_farmers_farmerratings_vendor_vendorratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productbidding',
            old_name='bitAmount',
            new_name='bidAmount',
        ),
    ]
