# Generated by Django 4.0.10 on 2023-03-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_rename_product_productinventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinventory',
            name='listedDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
