# Generated by Django 4.0.10 on 2023-03-18 14:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0007_alter_productinventory_listeddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinventory',
            name='productId',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
