# Generated by Django 4.0.10 on 2023-03-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0008_alter_productinventory_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinventory',
            name='expiryDate',
            field=models.DateField(null=True),
        ),
    ]
