# Generated by Django 4.0.10 on 2023-03-24 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0008_rename_invetoryid_productbidding_inventoryid'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbidding',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 3, 24, 10, 36, 59, 98667)),
            preserve_default=False,
        ),
    ]
