# Generated by Django 4.0.10 on 2023-03-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0009_alter_productinventory_expirydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinventory',
            name='images',
            field=models.TextField(default='', null=True),
        ),
    ]
