# Generated by Django 4.0.10 on 2023-03-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0010_alter_productinventory_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='allProductList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('products', models.CharField(max_length=254)),
                ('imgage', models.ImageField(null=True, upload_to='farmers/allProductList')),
            ],
        ),
        migrations.RenameField(
            model_name='productinventory',
            old_name='description',
            new_name='productDescription',
        ),
        migrations.RenameField(
            model_name='productinventory',
            old_name='expiryDate',
            new_name='productExpiryDate',
        ),
        migrations.RenameField(
            model_name='productinventory',
            old_name='images',
            new_name='productImages',
        ),
        migrations.RenameField(
            model_name='productinventory',
            old_name='listedDate',
            new_name='productListedDate',
        ),
        migrations.RenameField(
            model_name='productinventory',
            old_name='name',
            new_name='productName',
        ),
        migrations.RenameField(
            model_name='productinventory',
            old_name='quantity',
            new_name='productQuantity',
        ),
    ]
