# Generated by Django 4.0.10 on 2023-03-20 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0011_allproductlist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userauth',
            old_name='roll',
            new_name='role',
        ),
    ]
