# Generated by Django 4.0.10 on 2023-03-24 10:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0011_alter_productbidding_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbidding',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 24, 10, 47, 57, 609649, tzinfo=utc)),
        ),
    ]
