# Generated by Django 4.0.10 on 2023-03-24 10:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0013_alter_productbidding_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbidding',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 24, 10, 57, 42, 746598, tzinfo=utc)),
        ),
    ]
