# Generated by Django 4.0.10 on 2023-03-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0015_alter_productbidding_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbidding',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
