# Generated by Django 4.0.10 on 2023-03-24 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0016_alter_productbidding_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productbidding',
            old_name='id',
            new_name='bidId',
        ),
    ]
