# Generated by Django 4.0.10 on 2023-03-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0017_rename_id_productbidding_bidid'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbidding',
            name='vendorName',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
